### ISSUE TITLE
mscConfirm Not Preventing Href to confirmation

### ISSUE THREAD

**Issue by ArchTaqi** [brijeshb42/medium-style-confirm#2]
I am trying to apply mscConfirm on an anchor tag, where upon click I want to confirm user that if he is sure,
Below is the simple code.

```
<a class="btn btn-success"
     onclick="javascript:return mscConfirm('Are you sure you want to start this application??', function(){return true;
                                })"
                                   href="any-page.html"

                                >Start</a>
```

What what happens, when i click on the link, confirm boxes apears and automatically redirects to the herf, before even I click Yes or No?

**Comment by brijeshb42** [comment]
No javascript code can block code execution without using default `alert`, `confirm` or `prompt`.
`medium-style-confirm` is no different. Using this, you cannot block javascript execution. That is why callbacks are used. To achieve what you are trying to use, you will have to use proper callbacks and `event.preventDefault()`.

Example HTML:

``` html
<a class="btn btn-success" href="any-page.html" onclick="confirmNavigation(event)">Start</a>
```

Javascript:

``` javascript
function confirmNavigation(e) {
  e.preventDefault();
  mscConfirm('Are you sure you want to start this application??', function() {
    window.location.href = e.target.href;
  });
}
```
